version: "3.8"

services:
  database:
    build: ./mysql
    ports:
      - 3306:3306

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - SQLALCHEMY_CONNECTION_STRING=mysql+mysqldb://root:midnight@database/midnight
    ports:
      - 8001:8000

  frontend:
    build: ./frontend
    ports:
      - 81:80

volumes:
  db: